server:
  port: 8080

spring:

  application:
    name: video_games_shop

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false

  datasource:
    url: jdbc:postgresql://localhost:5432/videogames_shop
    username: postgres
    password: ${DB_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
